---
- name: Lighthouse pre-install dependencies
  hosts: lighthouse
  pre_tasks:
    - name: Install epel-release
      become: true
      ansible.builtin.yum:
        name: epel-release
        state: present
    - name: Install nginx
      become: true
      ansible.builtin.yum:
        name: nginx
        state: present
    - name: Create nginx config
      become: true
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: 0644
    - name: Install git
      become: true
      ansible.builtin.yum:
        name: git
        state: present

- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse
- name: Install Vector
  hosts: vector
  roles:
    - vector-role
- name: Install Lighthouse
  hosts: lighthouse
  roles:
    - lighthouse-role

- name: Lighthouse post-install dependencies
  hosts: lighthouse
  post_tasks:
    - name: Restart nginx
      become: true
      ansible.builtin.service:
        name: nginx
        state: restarted
    - name: Firewall config
      become: true
      ansible.builtin.shell: |
        firewall-cmd --permanent --zone=public --add-service=http
        firewall-cmd --reload
      changed_when: true
