---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 192.168.3.18
vector:
  hosts:
    vector-01:
      ansible_host: 192.168.3.18
lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 192.168.3.18